# Generated by Django 3.2.7 on 2021-11-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('movies', 'movies'), ('antique', 'antique'), ('magical', 'magical'), ('rare item', 'rare item'), ('fashion', 'fashion'), ('toys', 'toys'), ('electronics', 'electronics')], default='movies', max_length=1000),
        ),
    ]
